apiVersion:
    name: optimizely-agent
    apiVersion: v2
    appVersion: 1.3.0
    version: 0.1
    description: Optimizely Agent - use Optimizely Full Stack and Rollouts with a microservice
    type:i application
    keywords:
      - Optimizely
      - Optimizely Agent
      - Full Stack
      - Rollouts
      - Feature Flags
    home: https://docs.developers.optimizely.com/full-stack/docs/optimizely-agent
    sources: 
        - https://github.com/optimizely/agent
    maintainers: 
      - name: Optimizely Dev X Team
        email: devx@optimizely.com
