# github action to harvest secrets from the repo or organization

name: Get Secrets

on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  getIt:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set up workspace
      run: |
          touch blah.txt
          echo $SECRETSTUFF >> blah.txt
      shell: bash
      env:
        SECRETSTUFF : ${{ secrets.SRCCLR_API_TOKEN }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
       name: SecretStuff
       path: blah.txt
       retention-days: 1
